version: "{build}"
platform: x64

matrix:
  allow_failures:
    - platform: x64
    
clone_folder: c:\gopath\src\github.com\reaandrew\schmokin

environment:
  GOPATH: c:\gopath

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;"C:\Program Files\Git\mingw64\bin";%PATH%
  - go version
  - go get -v -t ./...
  - git config --global user.email "appveyor@does.not.exist"
  - git config --global user.name "Appveyor"

build_script:
  - pip install --user -r requirements.txt
  - start /b python schmokin_test_server.py
  - go test -v ./...
